=== Gedanken-Versichert/web/src/config.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"description": "Configuration file for the Gedanken Versichert website",
	"properties": {
		"title": {
			"type": "string",
			"description": "The title of the site."
		},
		"description": {
			"type": "string",
			"description": "A short description of the site, optional."
		},
		"sections": {
			"type": "array",
			"description": "Array of sections, eg. Mathematik, Physik, etc.",
			"items": {
				"type": "object",
				"description": "A section containing links and possibly subsections",
				"properties": {
					"title": {
						"type": "string",
						"description": "The title of the section"
					},
					"links": {
						"type": "array",
						"description": "The array of links in each section",
						"items": {
							"type": "object",
							"description": "A link to a program or resource",
							"properties": {
								"title": {
									"type": "string",
									"description": "The title of the link"
								},
								"url": {
									"type": "string",
									"description": "A URL to the link"
								}
							},
							"required": ["title", "url"]
						}
					}
				},
				"required": ["title", "links"]
			}
		},
		"touchWarning": {
			"type": "string",
			"description": "The warning to be shown to users with touch screens."
		}
	},
	"required": ["title", "description", "sections", "touchWarning"]
}

=== Gedanken-Versichert/web/src/config.json
{
    "title": "Gedanken Versichert",
    "description": "",
    "sections": [
        {
            "title": "Mathematik",
            "links": [
                {
                    "title": "Primzahl-Test - von Botond",
                    "url": "/programs/prime-test/"
                }
            ],
            "sections": []
        },
        {
            "title": "Physik",
            "links": [
                {
                    "title": "Bewegung eines Balles - von Bendegúz & Botond",
                    "url": "/programs/parabola-motion/"
                },
                {
                    "title": "Newtonsche Gravitation - von Bendegúz",
                    "url": "/programs/newtonsche-gravitation/"
                },
                {
                    "title": "Two-body simulation using Verlet Integration - von Bendegúz & Botond",
                    "url": "/programs/two-body-simulation/"
                }
            ],
            "sections": []
        },
        {
            "title": "Programmierung",
            "links": [
                {
                    "title": "Vortex-Graphik - von Bendegúz",
                    "url": "/programs/random-points/"
                }
            ],
            "sections": []
        }
    ],
    "touchWarning": "WARNUNG: Diese Programme funktionieren nicht mit Touchscreens"
}
